name: Build and Self-Sign APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission
      run: chmod +x ./gradlew

    - name: Generate debug keystore
      run: |
        keytool -genkey -v \
          -keystore debug.keystore \
          -storepass android \
          -alias androiddebugkey \
          -keypass android \
          -dname "CN=Android Debug,O=Android,C=US" \
          -keyalg RSA -keysize 2048 -validity 10000

    - name: Set signing env
      run: |
        echo "KEYSTORE_PATH=$(pwd)/debug.keystore" >> $GITHUB_ENV
        echo "KEYSTORE_PASSWORD=android" >> $GITHUB_ENV
        echo "KEY_ALIAS=androiddebugkey" >> $GITHUB_ENV
        echo "KEY_PASSWORD=android" >> $GITHUB_ENV

    - name: Build signed APK
      run: ./gradlew assembleRelease

    - name: Sign APK manually (если gradle не подписывает)
      run: |
        APK=$(find . -name "*-release-unsigned.apk" | head -n 1)
        echo "Found APK: $APK"
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore debug.keystore \
          -storepass android \
          -keypass android \
          "$APK" androiddebugkey

    - name: Verify APK signature
      run: |
        APK=$(find . -name "*-release-unsigned.apk" | head -n 1)
        jarsigner -verify "$APK"

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-apk
        path: |
          **/*-release-unsigned.apk
