name: Build AmneziaWG Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease --no-daemon --stacktrace

    - name: List all APK files
      run: find . -type f -name "*.apk"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaWG-release
        path: '**/build/outputs/apk/**/*.apk'
