name: Build Full Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Assemble all release APKs
      run: ./gradlew assembleRelease --no-daemon --stacktrace

    - name: Find all APKs
      run: find . -name "*.apk"

    - name: Upload all APKs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: All-Release-APKs
        path: '**/*.apk'
